### ISSUE TITLE
Decoding failure when decoding commit response.

### ISSUE THREAD

**Issue by bszwej** [zalando-incubator/kanadi#39]
When committing a cursor using the high level API (Subscription) when **an empty batch arrived**, I receive the following error:
```
DecodingFailure at .items[0].partition: Attempt to decode value on failed cursor
DecodingFailure at .items[0].offset: Attempt to decode value on failed cursor
DecodingFailure at .items[0].event_type: Attempt to decode value on failed cursor
DecodingFailure at .items[0].cursor_token: Attempt to decode value on failed cursor
```

However, if the batch contains events, I receive:
```
Message entity must not be empty.
```

I can confirm, that despite the error log messages, the cursor is committed correctly. I'm using Kanadi version 0.2.3.

I prepared a minimal reproduction of this bug: https://github.com/bszwej/kanadi-commit-bug

**Comment by mdedetrich** [comment]
Closed in PR, thanks for reporting!
