### ISSUE TITLE
modifySourceFunction is not used in Subscriptions.eventsStreamedManaged

### ISSUE THREAD

**Issue by gamsd** [zalando-incubator/kanadi#70]
In `Subscriptions.eventsStreamedManaged()`, the `modifySourceFunction` parameter is not passed along to the underlying `Subscriptions.eventsStreamed()` call. That means it's never called and the source never modified.

**Comment by gamsd** [comment]
@mdedetrich Fix is a one-liner, but testing is way more involved. Is this the kind of thing that you would consider merging without tests?

**Comment by mdedetrich** [comment]
@gamsd It shouldn't be too hard to test, you can supply a `modifySourceFunction` that just returns itself while setting an `AtomicBoolean` and then check that the `AtomicBoolean` is true.

I can also set up a PR to do this, shouldn't be too hard
