### ISSUE TITLE
Kanadi does not reconnect to nakadi

### ISSUE THREAD

**Issue by Refal** [zalando-incubator/kanadi#80]
From logs I can see:
`INFO --- org.zalando.kanadi.api.Subscriptions : Server disconnected Nakadi stream, reconnecting in 30 seconds Old StreamId`
And nothing happens then
Looks like at this line: [https://github.com/zalando-incubator/kanadi/blob/master/src/main/scala/org/zalando/kanadi/api/Subscriptions.scala#L1378](reconnect)
If  exception happened then there is no code to correctly restart stream again

**Comment by mdedetrich** [comment]
Found out the cause of this issue, closing
